spring:

  # TODO: h2 console ? ????? commit? ?
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA ??
  jpa:
    hibernate: # hibernate ?? ??
      ddl-auto: create # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true

  config:
    import:
      - classpath:/application-security.yml
    activate:
      on-profile: local


# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ?? ???? ????? ???? ??

server:
  port: 8080
